### ISSUE TITLE
@aws-amplify/ui-angular@2.1.2 fails to compile

### ISSUE THREAD

**Issue by anurag-roy** [aws-amplify/amplify-ui#1375]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

Webpack 5

### Please describe your bug.

The latest angular package fails to build/compile.

```
Uncaught Error: Type AmplifyAuthenticatorModule does not have 'ɵmod' property.
    at getNgModuleDef (vendor.js:272109:11)
    at recurse (vendor.js:296109:17)
    at recurse (vendor.js:296125:9)
    at registerNgModuleType (vendor.js:296104:3)
    at new NgModuleFactory (vendor.js:296245:7)
    at compileNgModuleFactory (vendor.js:300855:25)
    at PlatformRef.bootstrapModule (vendor.js:301163:12)
    at Module.14431 (main.js:3583:74)
    at __webpack_require__ (runtime.js:23:42)
    at __webpack_exec__ (main.js:3978:48)
```

### What's the expected behaviour?

It should compile successfully.

### Help us reproduce the bug!

Tried to reproduce on StackBlitz: https://stackblitz.com/edit/angular-ivy-aa1yl1?file=src/app/app.component.html

It shows the following error:

```
Error in turbo_modules/@aws-amplify/ui-angular@2.1.2/lib/components/authenticator/authenticator.module.d.ts (1:22)
Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the dependency (@aws-amplify/ui-angular) which declares AmplifyAuthenticatorModule has not been processed correctly by ngcc.
```

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by anurag-roy** [comment]
Not sure what the issue was, but I tried it again and now it seems to be fixed!
