### ISSUE TITLE
VueCli build failure

### ISSUE THREAD

**Issue by jacoblogan** [aws-amplify/amplify-ui#2038]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Other

### How is your app built?

vuecli

### Please describe your bug.

There is a build failure on the vuecli canary application with the following stack trace
```
  ERROR  TypeError: StackFrame is not a constructor
TypeError: StackFrame is not a constructor
    at Object.<anonymous> (/home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/error-stack-parser/error-stack-parser.js:76:24)
    at Array.map (<anonymous>)
    at Object.ErrorStackParser$$parseV8OrIE [as parseV8OrIE] (/home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/error-stack-parser/error-stack-parser.js:56:29)
    at Object.ErrorStackParser$$parse [as parse] (/home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/error-stack-parser/error-stack-parser.js:31:29)
    at getOriginalErrorStack (/home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:31:29)
    at extractError (/home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:22:20)
    at Array.map (<anonymous>)
    at processErrors (/home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/@soda/friendly-errors-webpack-plugin/src/core/transformErrors.js:31:17)
    at FriendlyErrorsWebpackPlugin.displayErrors (/home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:97:29)
    at doneFn (/home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:57:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (/home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/tapable/lib/Hook.js:154:20)
    at /home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/webpack/lib/Compiler.js:298:10
    at /home/runner/work/amplify-ui/amplify-ui/canary/apps/vue/vuecli/node_modules/webpack/lib/Compiler.js:485:14
```

### What's the expected behaviour?

No build error

### Help us reproduce the bug!

Failure found in github canary build

**Comment by jacoblogan** [comment]
This is believed to be due to an upstream dependency that was recently updated.  This issue is being worked on.  Please comment below if you are also experiencing this issue.
