### ISSUE TITLE
Amplify and Vue 3 doesn’t publish or build

### ISSUE THREAD

**Issue by goldbergmoshe** [aws-amplify/amplify-ui#2042]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Vue Cli Webpack

### Please describe your bug.

When I try create a Vue 3 project with Amplify it serves without errors, however when you try publish or build I get the following errors;

```
ERROR TypeError: ErrorStackParser.parse is not a function
TypeError: ErrorStackParser.parse is not a function
at getOriginalErrorStack (/Users/xxx/fullstack/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:31:29)
at extractError (/Users/xxx/fullstack/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:22:20)
at Array.map ()
at processErrors (/Users/xxx/fullstack/node_modules/@soda/friendly-errors-webpack-plugin/src/core/transformErrors.js:31:17)
at FriendlyErrorsWebpackPlugin.displayErrors (/Users/xxx/fullstack/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:97:29)
at doneFn (/Users/xxx/fullstack/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:57:14)
at Hook.eval [as callAsync] (eval at create (/Users/xxx/fullstack/node_modules/tapable/lib/HookCodeFactory.js:33:10), :18:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/xxx/fullstack/node_modules/tapable/lib/Hook.js:18:14)
at /Users/xxx/fullstack/node_modules/webpack/lib/Compiler.js:498:23
at Compiler.emitRecords (/Users/xxx/fullstack/node_modules/webpack/lib/Compiler.js:919:5)
/usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:174
err = new Error(Command failed: ${joinedCmd}${output});
^

Error: Command failed: npm run build
at makeError (/usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:174:9)
at /usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:278:16
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async runNpmScript (/usr/local/lib/node_modules/@vue/cli/lib/util/runNpmScript.js:17:10) {
code: 1,
stdout: null,
stderr: null,
failed: true,
signal: null,
cmd: 'npm run build',
timedOut: false,
killed: false
}

Node.js v17.7.2
```
The UI library seems to be causing this. Would really appreciate help. 

### What's the expected behaviour?

I would expect the demo project to build successfully with vue 3 and amplify as advertised!

### Help us reproduce the bug!

Just follow the get started guide on the amplify website with vue. 

https://docs.amplify.aws/start/getting-started/data-model/q/integration/vue/#create-graphql-api-and-database

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by wlee221** [comment]
Hi! This is a known upstream issue: https://github.com/stacktracejs/error-stack-parser/issues/80.

It seems they just released a fix 4 hours ago; can you try reinstalling your `node_modules` folder and let us know if the problem persists?

```bash
# on NPM:
rm -rf package-lock.json node_modules/ && npm install
# on yarn:
rm -rf yarn.lock node_moudles && yarn
```
