### ISSUE TITLE
Error: Cannot find module '@aws-sdk/util-credentials' on Amplify Hosting next.js

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-ui#3136]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Next.js

### Please describe your bug.

While deploying my app to amplify hosting using the new next.js compute feature I am getting the below stack trace.

I am using the following packages.
"@aws-amplify/ui-react": "^4.1.0",
"next": "^12.2.5",
"aws-amplify": "^5.0.4",

```
2022-12-05T05:25:49.397Z [INFO]: info  - Compiled successfully
2022-12-05T05:25:49.399Z [INFO]: info  - Collecting page data...
**2022-12-05T05:25:52.033Z [WARNING]: Error: Cannot find module '@aws-sdk/util-credentials'
                                    Require stack:**
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/runtimeConfig.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/LocationClient.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/Location.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/geo/lib/Providers/AmazonLocationServiceProvider.js
                                    - /src/monorepo/node_modules/@aws-amplify/geo/lib/Geo.js
                                    - /src/monorepo/node_modules/@aws-amplify/geo/lib/index.js
                                    - /src/monorepo/node_modules/aws-amplify/lib/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/ui/dist/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/ui-react-core/dist/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/ui-react/dist/index.js
                                    - /src/monorepo/apps/admin/.next/server/pages/_app.js
                                    - /src/monorepo/node_modules/next/dist/server/require.js
                                    - /src/monorepo/node_modules/next/dist/server/load-components.js
                                    - /src/monorepo/node_modules/next/dist/export/worker.js
                                    - /src/monorepo/node_modules/next/dist/build/worker.js
                                    - /src/monorepo/node_modules/next/dist/compiled/jest-worker/processChild.js
                                    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
                                    at Function.mod._resolveFilename (/src/monorepo/node_modules/next/dist/build/webpack/require-hook.js:27:32)
                                    at Function.mod._resolveFilename (/src/monorepo/node_modules/next/dist/build/webpack/require-hook.js:27:32)
                                    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
                                    at Module.require (internal/modules/cjs/loader.js:974:19)
                                    at require (internal/modules/cjs/helpers.js:101:18)
                                    at Object.<anonymous> (/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js:7:28)
                                    at Module._compile (internal/modules/cjs/loader.js:1085:14)
                                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
                                    at Module.load (internal/modules/cjs/loader.js:950:32) {
                                    code: 'MODULE_NOT_FOUND',
                                    requireStack: [
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/runtimeConfig.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/LocationClient.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/Location.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/geo/lib/Providers/AmazonLocationServiceProvider.js',
                                    '/src/monorepo/node_modules/@aws-amplify/geo/lib/Geo.js',
                                    '/src/monorepo/node_modules/@aws-amplify/geo/lib/index.js',
                                    '/src/monorepo/node_modules/aws-amplify/lib/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/ui/dist/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/ui-react-core/dist/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/ui-react/dist/index.js',
                                    '/src/monorepo/apps/admin/.next/server/pages/_app.js',
                                    '/src/monorepo/node_modules/next/dist/server/require.js',
                                    '/src/monorepo/node_modules/next/dist/server/load-components.js',
                                    '/src/monorepo/node_modules/next/dist/export/worker.js',
                                    '/src/monorepo/node_modules/next/dist/build/worker.js',
                                    '/src/monorepo/node_modules/next/dist/compiled/jest-worker/processChild.js'
                                    ]
                                    }
2022-12-05T05:25:52.035Z [WARNING]: Error: Cannot find module '@aws-sdk/util-credentials'
                                    Require stack:
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/runtimeConfig.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/LocationClient.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/Location.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/geo/lib/Providers/AmazonLocationServiceProvider.js
                                    - /src/monorepo/node_modules/@aws-amplify/geo/lib/Geo.js
                                    - /src/monorepo/node_modules/@aws-amplify/geo/lib/index.js
                                    - /src/monorepo/node_modules/aws-amplify/lib/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/ui/dist/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/ui-react-core/dist/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/ui-react/dist/index.js
                                    - /src/monorepo/apps/admin/.next/server/pages/_app.js
                                    - /src/monorepo/node_modules/next/dist/server/require.js
                                    - /src/monorepo/node_modules/next/dist/server/load-components.js
                                    - /src/monorepo/node_modules/next/dist/export/worker.js
                                    - /src/monorepo/node_modules/next/dist/build/worker.js
                                    - /src/monorepo/node_modules/next/dist/compiled/jest-worker/processChild.js
                                    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
                                    at Function.mod._resolveFilename (/src/monorepo/node_modules/next/dist/build/webpack/require-hook.js:27:32)
                                    at Function.mod._resolveFilename (/src/monorepo/node_modules/next/dist/build/webpack/require-hook.js:27:32)
                                    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
                                    at Module.require (internal/modules/cjs/loader.js:974:19)
                                    at require (internal/modules/cjs/helpers.js:101:18)
                                    at Object.<anonymous> (/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js:7:28)
                                    at Module._compile (internal/modules/cjs/loader.js:1085:14)
                                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
                                    at Module.load (internal/modules/cjs/loader.js:950:32) {
                                    code: 'MODULE_NOT_FOUND',
                                    requireStack: [
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/runtimeConfig.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/LocationClient.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/Location.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/geo/lib/Providers/AmazonLocationServiceProvider.js',
                                    '/src/monorepo/node_modules/@aws-amplify/geo/lib/Geo.js',
                                    '/src/monorepo/node_modules/@aws-amplify/geo/lib/index.js',
                                    '/src/monorepo/node_modules/aws-amplify/lib/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/ui/dist/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/ui-react-core/dist/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/ui-react/dist/index.js',
                                    '/src/monorepo/apps/admin/.next/server/pages/_app.js',
                                    '/src/monorepo/node_modules/next/dist/server/require.js',
                                    '/src/monorepo/node_modules/next/dist/server/load-components.js',
                                    '/src/monorepo/node_modules/next/dist/export/worker.js',
                                    '/src/monorepo/node_modules/next/dist/build/worker.js',
                                    '/src/monorepo/node_modules/next/dist/compiled/jest-worker/processChild.js'
                                    ]
                                    }
2022-12-05T05:25:52.036Z [WARNING]: 
2022-12-05T05:25:52.036Z [WARNING]: > Build error occurred
2022-12-05T05:25:52.038Z [WARNING]: Error: Failed to collect page data for /auth
                                    at /src/monorepo/node_modules/next/dist/build/utils.js:916:15
                                    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
                                    type: 'Error'
                                    }
2022-12-05T05:25:52.149Z [WARNING]: error Command failed with exit code 1.
2022-12-05T05:25:52.149Z [INFO]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022-12-05T05:25:52.156Z [ERROR]: !!! Build failed
2022-12-05T05:25:52.156Z [ERROR]: !!! Non-Zero Exit Code detected
2022-12-05T05:25:52.157Z [INFO]: # Starting environment caching...
2022-12-05T05:25:52.157Z [INFO]: # Uploading environment cache artifact...
2022-12-05T05:25:52.237Z [INFO]: # Uploaded environment cache artifact
2022-12-05T05:25:52.237Z [INFO]: # Environment caching completed
Terminating logging...
```

### What's the expected behaviour?

either @aws-sdk/credential-provider-sso is not used or if it should be used it would be able to find all of it's dependencies.

### Help us reproduce the bug!

- Create next app with the following dependencies

"@aws-amplify/ui-react": "^4.1.0",
"next": "^12.2.5",
"aws-amplify": "^5.0.4",

- Deploy to amplify hosting using the new next.js

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

It's worth noting that on my local machine the @aws-sdk/client-location package does not even use/have @aws-sdk/credential-provider-sso it only seems to install credential-provider-ini/node/process

**Comment by 0618** [comment]
Hey @oste ! Thanks for letting us know the issue. Just to clarify, is your app in a monorepo?

You can find it under "Environment variables" --> "AMPLIFY_MONOREPO_APP_ROOT". 

I wonder if that's the same issue as https://github.com/aws-amplify/amplify-hosting/issues/3153

**Comment by oste** [comment]
hi @0618 yes the app having the problem is a monorepo.

**Comment by 0618** [comment]
Thanks @oste ! It's a known issue in Amplify Hosting. We've been tracking the fixing progress in https://github.com/aws-amplify/amplify-hosting/issues/3153 . Please follow it to stay tuned. 

We apologize for this issue.

**Comment by mojansen** [comment]
@0618  since the comments in the linked issue are locked, I'm adding one here. Are there any updates on this?

**Comment by reesscot** [comment]
@mojansen We don't have any update yet, but I commented on the ticket for you: https://github.com/aws-amplify/amplify-hosting/issues/3153#issuecomment-1404139705
