### ISSUE TITLE
rowspan and colspan on Table throws errors.

### ISSUE THREAD

**Issue by anandkumarpatel** [aws-amplify/amplify-ui#4284]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Primitive components

### How is your app built?

Create React App 

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari

### Please describe your bug.

Getting errors when trying to use Table with rowspan following the example here: https://ui.docs.amplify.aws/react/components/table#spanning-multiple-columns-or-rows

```
Warning: Invalid DOM property `rowspan`. Did you mean `rowSpan`?
```
The table renders correctly, but the errors in the console should not be there.

I tried changing to `rowSpan` but that does not merge the rows as `rowspan` does.

### What's the expected behaviour?

The table renders without errors in the console

### Help us reproduce the bug!

run this example: https://ui.docs.amplify.aws/react/components/table#spanning-multiple-columns-or-rows

### Code Snippet

import { Table, TableBody, TableCell, TableRow } from '@aws-amplify/ui-react';

export const SpanExample = () => (
  <Table variation="bordered">
    <TableBody>
      <TableRow>
        <TableCell />
        <TableCell />
        <TableCell
          colspan="2"
        />
      </TableRow>
      <TableRow>
        <TableCell
          rowspan="3"
        />
        <TableCell />
        <TableCell />
        <TableCell
          rowspan="3"
        />
      </TableRow>
      <TableRow>
        <TableCell />
        <TableCell />
      </TableRow>
      <TableRow>
        <TableCell
          colspan="3"
        />
      </TableRow>
    </TableBody>
  </Table>
);

### Console log output

Warning: Invalid DOM property `rowspan`. Did you mean `rowSpan`?
    at td
    at http://localhost:3006/static/js/bundle.js:244087:11
    at http://localhost:3006/static/js/bundle.js:243601:11
    at tr
    at http://localhost:3006/static/js/bundle.js:244087:11
    at http://localhost:3006/static/js/bundle.js:243678:17
    at tbody
    at http://localhost:3006/static/js/bundle.js:244087:11
    at http://localhost:3006/static/js/bundle.js:243563:17
    at table

**Comment by zchenwei** [comment]
Hi @anandkumarpatel, thanks for reporting this issue! I can reproduce this issue. The root cause is we did not type the props correctly:
```ts
  colspan?: Pick<React.HTMLProps<HTMLTableCellElement>, 'colSpan'>;
  rowspan?: Pick<React.TdHTMLAttributes<HTMLTableCellElement>, 'rowSpan'>;
```
The `Pick` utility type will create an interface type `{ rowSpan?: number | undefined }` instead of a primitive type like `number | undefined`. The latter is what we expect. We will fix the issue soon and let you know.
