### ISSUE TITLE
NPM/Yarn typo prevents installation of ui-react

### ISSUE THREAD

**Issue by SLYtiger16** [aws-amplify/amplify-ui#5080]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

CRA/Node

### Which region are you seeing the problem in?

NA

### Please describe your bug.

"'typescrip" missing 't'

NPM:
npm i @aws-amplify/ui-react
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/typescrip - Not found
npm ERR! 404 
npm ERR! 404  **'typescrip@^5.4.2'** is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Yarn:
 yarn add @aws-amplify/ui-react
yarn add v1.22.22
[1/4] Resolving packages...
error Error: https://registry.yarnpkg.com/**typescrip**: Not found
    at params.callback [as _callback] (/home/kmeado/.nvm/versions/node/v20.11.1/lib/node_modules/yarn/lib/cli.js:66680:18)
    at self.callback (/home/kmeado/.nvm/versions/node/v20.11.1/lib/node_modules/yarn/lib/cli.js:141410:22)
    at Request.emit (node:events:518:28)
    at Request.<anonymous> (/home/kmeado/.nvm/versions/node/v20.11.1/lib/node_modules/yarn/lib/cli.js:142382:10)
    at Request.emit (node:events:518:28)
    at IncomingMessage.<anonymous> (/home/kmeado/.nvm/versions/node/v20.11.1/lib/node_modules/yarn/lib/cli.js:142304:12)
    at Object.onceWrapper (node:events:632:28)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### What's the expected behaviour?

Proper NPM install

### Help us reproduce the bug!

Attempt to install it from NPM

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by hbuchel** [comment]
Hi @SLYtiger16 I'm unable to reproduce this issue in a fresh CRA install. What I tried:

```
npx create-react-app my-app
```
Then, inside of my-app:
```
npm i @aws-amplify/ui-react
```

Is it possible your package.json has a typo?

**Comment by SLYtiger16** [comment]
After hours of review it was a package.json typo (facepalm).
