### ISSUE TITLE
ui-react@2.0.0: Unable to build with vite

### ISSUE THREAD

**Issue by thatsnotright** [aws-amplify/amplify-ui#849]
I am trying to use vite to bundle our app, switching from a webpack build.  I had to upgrade a bunch of things, including ui-react, and it runs in development mode now but when running vite build, I get the following:

```
error during build:
Error: 'default' is not exported by node_modules/@aws-amplify/ui-react/node_modules/autoprefixer/lib/autoprefixer.js, imported by node_modules/@aws-amplify/ui-react/dist/esm/index.js
    at error (/home/robelsner/rise/node_modules/rollup/dist/shared/rollup.js:158:30)
    at Module.error (/home/robelsner/rise/node_modules/rollup/dist/shared/rollup.js:12382:16)
    at Module.traceVariable (/home/robelsner/rise/node_modules/rollup/dist/shared/rollup.js:12767:29)
    at ModuleScope.findVariable (/home/robelsner/rise/node_modules/rollup/dist/shared/rollup.js:11559:39)
    at Identifier.bind (/home/robelsner/rise/node_modules/rollup/dist/shared/rollup.js:6419:40)
    at ArrayExpression.bind (/home/robelsner/rise/node_modules/rollup/dist/shared/rollup.js:5021:31)
    at CallExpression.bind (/home/robelsner/rise/node_modules/rollup/dist/shared/rollup.js:5021:31)
    at CallExpression.bind (/home/robelsner/rise/node_modules/rollup/dist/shared/rollup.js:9396:15)
    at VariableDeclarator.bind (/home/robelsner/rise/node_modules/rollup/dist/shared/rollup.js:5025:23)
    at VariableDeclaration.bind (/home/robelsner/rise/node_modules/rollup/dist/shared/rollup.js:5021:31)

```

If I add 'autoprefixer' to the excludes in vite I can work around this problem.

```
  build: {
    outDir: '../dist',
    rollupOptions: {
      external: ['autoprefixer'], 
```

but this doesn't work when I build the bundle, 

```
Uncaught TypeError: Failed to resolve module specifier "autoprefixer". Relative references must start with either "/", "./", or "../".
```

What am I missing or doing wrong?  It seems other people have this working in vue and angular.

**Comment by thatsnotright** [comment]
I think it's maybe related to npm workspaces pulling in an old version of autoprefixer, and not using the version the ui-react project specifies as a dependency.
